name: base_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  module_external_dependencies:
    path: '../module_external_dependencies'

  module_home:
    path: '../module_home'

  module_welcome:
    path: '../module_welcome'

  module_commons:
    path: '../module_commons'

  module_core:
    path: '../module_core'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter/Inter-Black.ttf
          weight: 900